services:

    bywulf_user_form_type_user:
        class: Bywulf\UserBundle\Form\Type\UserType
        tags: ['form.type']

    bywulf_user_security_user_checker:
        class: Bywulf\UserBundle\Security\UserChecker

    Bywulf\UserBundle\Controller\:
        resource: '../../Controller/'
        autowire: true
        tags: ['controller.service_arguments']